"""PostgreSQL-backed account authentication and role checks for ROIP."""

import os
import re
from datetime import datetime, timezone

from werkzeug.security import check_password_hash, generate_password_hash
from psycopg.types.json import Jsonb

from roip_search.db import get_pool


VALID_ROLES = {"admin", "user"}
USERNAME_RE = re.compile(r"^[A-Za-z0-9_.@-]{3,80}$")


def initialize_auth_tables():
    """Create auth tables and ensure the bootstrap administrator exists."""
    username = (os.getenv("ADMIN_USERNAME", "admin") or "admin").strip().lower()
    password = os.getenv("ADMIN_PASSWORD", "admin1234!") or "admin1234!"
    if not USERNAME_RE.fullmatch(username):
        raise RuntimeError("ADMIN_USERNAME must be 3-80 characters: letters, numbers, _, ., @ or -")
    if len(password) < 8:
        raise RuntimeError("ADMIN_PASSWORD must be at least 8 characters")

    with get_pool().connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS app_users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(80) NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role VARCHAR(16) NOT NULL DEFAULT 'user'
                    CHECK (role IN ('admin', 'user')),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                last_login_at TIMESTAMPTZ
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_audit_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                actor_username VARCHAR(80) NOT NULL,
                action VARCHAR(80) NOT NULL,
                target_username VARCHAR(80),
                occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                ip INET,
                details JSONB NOT NULL DEFAULT '{}'::jsonb
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_room_permissions (
                username VARCHAR(80) NOT NULL REFERENCES app_users(username) ON DELETE CASCADE,
                station_id INTEGER NOT NULL,
                channel_id INTEGER NOT NULL,
                channel_name TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (username, station_id, channel_id)
            )
            """
        )
        conn.execute(
            """
            INSERT INTO app_users (username, password_hash, role)
            VALUES (%s, %s, 'admin')
            ON CONFLICT (username) DO NOTHING
            """,
            (username, generate_password_hash(password)),
        )
        conn.commit()


def authenticate_user(username, password):
    username = (username or "").strip().lower()
    if not username or not password:
        return None
    with get_pool().connection() as conn:
        user = conn.execute(
            """
            SELECT id, username, password_hash, role, is_active
            FROM app_users WHERE username=%s
            """,
            (username,),
        ).fetchone()
        if not user or not user["is_active"] or not check_password_hash(user["password_hash"], password):
            return None
        conn.execute(
            "UPDATE app_users SET last_login_at=%s, updated_at=%s WHERE id=%s",
            (datetime.now(timezone.utc), datetime.now(timezone.utc), user["id"]),
        )
        conn.commit()
        return {
            "id": user["id"],
            "username": user["username"],
            "role": user["role"],
        }


def list_users():
    with get_pool().connection() as conn:
        rows = conn.execute(
            """
            SELECT id, username, role, is_active, created_at, last_login_at
            FROM app_users ORDER BY username
            """
        ).fetchall()
        permissions = conn.execute(
            """
            SELECT username, station_id, channel_id, channel_name
            FROM user_room_permissions
            ORDER BY username, station_id, channel_id
            """
        ).fetchall()
    grouped = {}
    for permission in permissions:
        grouped.setdefault(permission["username"], []).append({
            "station_id": int(permission["station_id"]),
            "channel_id": int(permission["channel_id"]),
            "channel_name": permission["channel_name"],
        })
    result = []
    for row in rows:
        item = dict(row)
        item["room_permissions"] = grouped.get(item["username"], [])
        result.append(item)
    return result


def create_user(username, password, role="user", is_active=True):
    username = (username or "").strip().lower()
    role = (role or "user").strip().lower()
    if not USERNAME_RE.fullmatch(username):
        raise ValueError("ชื่อผู้ใช้ต้องมี 3-80 ตัวอักษร และใช้ได้เฉพาะ A-Z, 0-9, _, ., @, -")
    if len(password or "") < 8:
        raise ValueError("รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร")
    if role not in VALID_ROLES:
        raise ValueError("บทบาทไม่ถูกต้อง")
    with get_pool().connection() as conn:
        try:
            row = conn.execute(
                """
                INSERT INTO app_users (username, password_hash, role, is_active)
                VALUES (%s, %s, %s, %s)
                RETURNING id, username, role, is_active, created_at, last_login_at
                """,
                (username, generate_password_hash(password), role, bool(is_active)),
            ).fetchone()
            conn.commit()
        except Exception:
            conn.rollback()
            raise ValueError("ชื่อผู้ใช้นี้มีอยู่แล้ว")
    return dict(row)


def update_user(user_id, role=None, password=None, is_active=None):
    assignments = []
    values = []
    if role is not None:
        role = str(role).strip().lower()
        if role not in VALID_ROLES:
            raise ValueError("บทบาทไม่ถูกต้อง")
        assignments.append("role=%s")
        values.append(role)
    if password is not None and password != "":
        if len(password) < 8:
            raise ValueError("รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร")
        assignments.append("password_hash=%s")
        values.append(generate_password_hash(password))
    if is_active is not None:
        assignments.append("is_active=%s")
        values.append(bool(is_active))
    if not assignments:
        raise ValueError("ไม่มีข้อมูลที่ต้องแก้ไข")
    assignments.append("updated_at=%s")
    values.append(datetime.now(timezone.utc))
    values.append(int(user_id))
    with get_pool().connection() as conn:
        row = conn.execute(
            f"UPDATE app_users SET {', '.join(assignments)} WHERE id=%s "
            "RETURNING id, username, role, is_active, created_at, last_login_at",
            values,
        ).fetchone()
        if not row:
            conn.rollback()
            raise ValueError("ไม่พบผู้ใช้")
        conn.commit()
    return dict(row)


def replace_user_room_permissions(user_id, rooms):
    """Replace the explicit room scope for one account.

    Admin accounts are still stored with assignments for transparency, but the
    search backend intentionally ignores the assignments for admin users.
    """
    cleaned = []
    seen = set()
    for room in rooms or []:
        if not isinstance(room, dict):
            raise ValueError("รูปแบบสิทธิ์ห้องไม่ถูกต้อง")
        try:
            station_id = int(room.get("station_id"))
            channel_id = int(room.get("channel_id"))
        except (TypeError, ValueError):
            raise ValueError("รหัสสถานีหรือห้องไม่ถูกต้อง")
        if station_id < 0 or channel_id < 0:
            raise ValueError("รหัสสถานีและห้องต้องไม่ติดลบ")
        key = (station_id, channel_id)
        if key in seen:
            continue
        seen.add(key)
        cleaned.append({
            "station_id": station_id,
            "channel_id": channel_id,
            "channel_name": str(room.get("channel_name") or "")[:200] or None,
        })

    with get_pool().connection() as conn:
        user = conn.execute(
            "SELECT id, username, role FROM app_users WHERE id=%s",
            (int(user_id),),
        ).fetchone()
        if not user:
            raise ValueError("ไม่พบผู้ใช้")
        conn.execute("DELETE FROM user_room_permissions WHERE username=%s", (user["username"],))
        for room in cleaned:
            conn.execute(
                """
                INSERT INTO user_room_permissions
                    (username, station_id, channel_id, channel_name)
                VALUES (%s, %s, %s, %s)
                """,
                (user["username"], room["station_id"], room["channel_id"], room["channel_name"]),
            )
        conn.commit()
    user["room_permissions"] = cleaned
    return dict(user)


def delete_user(user_id):
    with get_pool().connection() as conn:
        row = conn.execute(
            "DELETE FROM app_users WHERE id=%s RETURNING username, role",
            (int(user_id),),
        ).fetchone()
        if not row:
            conn.rollback()
            raise ValueError("ไม่พบผู้ใช้")
        if row["role"] == "admin":
            count = conn.execute(
                "SELECT COUNT(*) AS count FROM app_users WHERE role='admin' AND is_active=TRUE"
            ).fetchone()["count"]
            if count < 1:
                conn.rollback()
                raise ValueError("ต้องเหลือ Admin ที่ใช้งานได้อย่างน้อย 1 บัญชี")
        conn.commit()
    return dict(row)


def count_active_admins():
    with get_pool().connection() as conn:
        return int(conn.execute(
            "SELECT COUNT(*) AS count FROM app_users WHERE role='admin' AND is_active=TRUE"
        ).fetchone()["count"])


def audit_user_action(actor_username, action, target_username=None, ip=None, details=None):
    with get_pool().connection() as conn:
        conn.execute(
            """
            INSERT INTO user_audit_events
                (actor_username, action, target_username, ip, details)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (actor_username, action, target_username, ip, Jsonb(details or {})),
        )
        conn.commit()
