CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS legacy_import_state (
    source_table TEXT PRIMARY KEY,
    last_source_id BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    container_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'user'
        CHECK (role IN ('admin', 'user')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS user_room_permissions (
    username VARCHAR(80) NOT NULL REFERENCES app_users(username) ON DELETE CASCADE,
    station_id INTEGER NOT NULL,
    channel_id INTEGER NOT NULL,
    channel_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (username, station_id, channel_id)
);

CREATE TABLE IF NOT EXISTS user_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username VARCHAR(80) NOT NULL,
    action VARCHAR(80) NOT NULL,
    target_username VARCHAR(80),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip INET,
    details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS audio_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key TEXT NOT NULL UNIQUE,
    mime_type TEXT NOT NULL DEFAULT 'audio/wav',
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    sha256 CHAR(64) NOT NULL,
    duration_ms INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    retention_until TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id TEXT NOT NULL UNIQUE,
    station_id INTEGER REFERENCES stations(id) ON DELETE SET NULL,
    channel_id INTEGER,
    channel_name TEXT,
    speaker_name TEXT NOT NULL,
    bot_name TEXT,
    message_type TEXT NOT NULL DEFAULT 'voice_transcript'
        CHECK (message_type IN ('voice_transcript', 'text_chat', 'tts', 'ptt', 'alert')),
    content_raw TEXT NOT NULL,
    content_corrected TEXT,
    content_normalized TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confidence REAL CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    language VARCHAR(16) NOT NULL DEFAULT 'th-TH',
    duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
    audio_asset_id BIGINT REFERENCES audio_assets(id) ON DELETE SET NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS keyword_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    keyword TEXT NOT NULL,
    matched_text TEXT,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (message_id, keyword)
);

CREATE TABLE IF NOT EXISTS alert_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'acknowledged', 'investigating', 'closed')),
    severity TEXT NOT NULL DEFAULT 'medium'
        CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    assignee_id TEXT,
    created_by TEXT NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acknowledged_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS case_messages (
    case_id BIGINT NOT NULL REFERENCES alert_cases(id) ON DELETE CASCADE,
    message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    added_by TEXT NOT NULL,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    note TEXT,
    PRIMARY KEY (case_id, message_id)
);

CREATE TABLE IF NOT EXISTS message_bookmarks (
    actor_id TEXT NOT NULL,
    message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    tags TEXT[] NOT NULL DEFAULT '{}',
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (actor_id, message_id)
);

CREATE TABLE IF NOT EXISTS transcript_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    revision_no INTEGER NOT NULL,
    corrected_text TEXT NOT NULL,
    reason TEXT,
    editor_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (message_id, revision_no)
);

CREATE TABLE IF NOT EXISTS saved_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL,
    name TEXT NOT NULL,
    query_json JSONB NOT NULL,
    notify_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (owner_id, name)
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip INET,
    details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS station_health_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id INTEGER REFERENCES stations(id) ON DELETE SET NULL,
    station_name TEXT,
    status VARCHAR(16) NOT NULL CHECK (status IN ('online', 'offline')),
    previous_status VARCHAR(16),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS system_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_chat_station_time
    ON chat_messages (station_id, occurred_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_time
    ON chat_messages (occurred_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_channel_time
    ON chat_messages (channel_id, occurred_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_station_channel_time
    ON chat_messages (station_id, channel_id, occurred_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_speaker_time
    ON chat_messages (LOWER(speaker_name), occurred_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_content_trgm
    ON chat_messages USING GIN (content_normalized gin_trgm_ops)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_chat_audio_time
    ON chat_messages (occurred_at DESC)
    WHERE audio_asset_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_keyword_time
    ON keyword_hits (keyword, detected_at DESC, message_id);
CREATE INDEX IF NOT EXISTS idx_keyword_message_keyword
    ON keyword_hits (message_id, keyword);
CREATE INDEX IF NOT EXISTS idx_keyword_trgm
    ON keyword_hits USING GIN (keyword gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_case_messages_message
    ON case_messages (message_id, case_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor_time
    ON audit_events (actor_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_station_health_time
    ON station_health_events (station_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_room_permissions_room
    ON user_room_permissions (station_id, channel_id, username);

INSERT INTO schema_migrations (version)
VALUES ('001_chat_search')
ON CONFLICT (version) DO NOTHING;
